import { WeatherAlert } from '@/types/weather';

// Mock weather alerts data for all seasons
// This data is used when NWS API is unavailable
// Includes winter storms, hurricanes, floods, wildfires, and severe thunderstorms

export const mockAllAlerts: WeatherAlert[] = [
  {
    id: 'mock-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-1',
      '@type': 'wx:Alert',
      id: 'mock-1',
      areaDesc: 'Dallas, Tarrant, Collin, Denton, Rockwall, Ellis, Johnson, Hood, Parker, Wise, TX',
      category: 'Met',
      response: 'Prepare',
      severity: 'Moderate',
      urgency: 'Expected',
      event: 'Winter Storm Watch',
      sender: 'W-NWS-NWSTG-2',
      senderName: 'NWS Fort Worth TX',
      headline: 'Winter Storm Watch for North Texas',
      description: 'A winter storm watch is in effect from Friday evening through Saturday evening for North Texas. Snow accumulation of 2-4 inches is expected, with localized amounts up to 6 inches possible. Travel could be very difficult, especially on bridges and overpasses.',
      instruction: 'Monitor the latest forecasts and prepare for possible travel disruptions. Ensure you have a winter emergency kit in your vehicle and at home.',
      messageType: 'Alert',
      certainty: 'Likely',
      url: 'https://weather.gov/fwd/winter',
      effective: new Date(Date.now() - 3600000).toISOString(),
      onset: new Date(Date.now() + 7200000).toISOString(),
      expires: new Date(Date.now() + 86400000).toISOString(),
      sent: new Date(Date.now() - 3600000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-97.334, 32.993],
          [-96.637, 32.993],
          [-96.637, 33.364],
          [-97.334, 33.364],
          [-97.334, 32.993],
        ],
      ],
    },
  },
  {
    id: 'mock-2',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-2',
      '@type': 'wx:Alert',
      id: 'mock-2',
      areaDesc: 'Chicago, Cook, DuPage, Kane, Lake, McHenry, Will, IL',
      category: 'Met',
      response: 'Avoid',
      severity: 'Severe',
      urgency: 'Immediate',
      event: 'Winter Storm Warning',
      sender: 'W-NWS-NWSTG-3',
      senderName: 'NWS Chicago IL',
      headline: 'Winter Storm Warning for Northern Illinois',
      description: 'A winter storm warning is in effect until Sunday morning. Heavy snow is expected with total accumulations of 6-10 inches. Wind gusts up to 35 mph will cause blowing and drifting snow, reducing visibility to less than a quarter mile at times.',
      instruction: 'Avoid all travel if possible. If you must travel, keep an extra flashlight, food, and water in your vehicle in case of an emergency.',
      messageType: 'Alert',
      certainty: 'Observed',
      url: 'https://weather.gov/lot/winter',
      effective: new Date(Date.now() - 7200000).toISOString(),
      onset: new Date(Date.now() - 3600000).toISOString(),
      expires: new Date(Date.now() + 43200000).toISOString(),
      sent: new Date(Date.now() - 7200000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-88.243, 41.508],
          [-87.524, 41.508],
          [-87.524, 42.023],
          [-88.243, 42.023],
          [-88.243, 41.508],
        ],
      ],
    },
  },
  {
    id: 'mock-3',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-3',
      '@type': 'wx:Alert',
      id: 'mock-3',
      areaDesc: 'New York, Kings, Queens, Bronx, Richmond, Nassau, Suffolk, Westchester, Rockland, Orange, NY',
      category: 'Met',
      response: 'Prepare',
      severity: 'Moderate',
      urgency: 'Expected',
      event: 'Winter Weather Advisory',
      sender: 'W-NWS-NWSTG-1',
      senderName: 'NWS New York NY',
      headline: 'Winter Weather Advisory for the Tri-State Area',
      description: 'A winter weather advisory is in effect from Saturday morning through Saturday evening. A mix of rain, sleet, and snow is expected, with snow accumulations of 1-3 inches possible. Ice accumulations up to one-tenth of an inch may cause slippery conditions.',
      instruction: 'Be prepared for slippery roads and limited visibility. Slow down and use caution while driving.',
      messageType: 'Alert',
      certainty: 'Possible',
      url: 'https://weather.gov/okx/winter',
      effective: new Date(Date.now() - 10800000).toISOString(),
      onset: new Date(Date.now() + 14400000).toISOString(),
      expires: new Date(Date.now() + 100800000).toISOString(),
      sent: new Date(Date.now() - 10800000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-74.259, 40.477],
          [-73.700, 40.477],
          [-73.700, 41.304],
          [-74.259, 41.304],
          [-74.259, 40.477],
        ],
      ],
    },
  },
  {
    id: 'mock-4',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-4',
      '@type': 'wx:Alert',
      id: 'mock-4',
      areaDesc: 'Seattle, King, Snohomish, Pierce, Kitsap, Thurston, WA',
      category: 'Met',
      response: 'Prepare',
      severity: 'Minor',
      urgency: 'Future',
      event: 'Snow Advisory',
      sender: 'W-NWS-NWSTG-17',
      senderName: 'NWS Seattle WA',
      headline: 'Snow Advisory for Western Washington',
      description: 'A snow advisory is in effect from Sunday night through Monday morning for Western Washington. Snow accumulations of 1-2 inches are expected in the lowlands, with 3-6 inches in the foothills. This could create slick conditions for the Monday morning commute.',
      instruction: 'Allow extra time for your Monday morning commute. Ensure your vehicle is equipped with winter tires or chains if traveling into the mountains.',
      messageType: 'Alert',
      certainty: 'Likely',
      url: 'https://weather.gov/sew/winter',
      effective: new Date(Date.now() + 21600000).toISOString(),
      onset: new Date(Date.now() + 36000000).toISOString(),
      expires: new Date(Date.now() + 129600000).toISOString(),
      sent: new Date(Date.now()).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-122.402, 47.448],
          [-121.805, 47.448],
          [-121.805, 47.735],
          [-122.402, 47.735],
          [-122.402, 47.448],
        ],
      ],
    },
  },
  {
    id: 'mock-5',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-5',
      '@type': 'wx:Alert',
      id: 'mock-5',
      areaDesc: 'Denver, Adams, Arapahoe, Douglas, Jefferson, Boulder, CO',
      category: 'Met',
      response: 'Avoid',
      severity: 'Severe',
      urgency: 'Immediate',
      event: 'Blizzard Warning',
      sender: 'W-NWS-NWSTG-7',
      senderName: 'NWS Denver CO',
      headline: 'Blizzard Warning for Denver Metro Area',
      description: 'A blizzard warning is in effect until Sunday afternoon for the Denver Metro area. Heavy snow with accumulations of 8-12 inches and wind gusts up to 50 mph will create blizzard conditions with visibility less than a quarter mile at times.',
      instruction: 'Avoid all travel. This is a dangerous winter storm that could strand motorists for hours. If you become stranded, stay in your vehicle and call for help.',
      messageType: 'Alert',
      certainty: 'Observed',
      url: 'https://weather.gov/den/winter',
      effective: new Date(Date.now() - 7200000).toISOString(),
      onset: new Date(Date.now() - 3600000).toISOString(),
      expires: new Date(Date.now() + 57600000).toISOString(),
      sent: new Date(Date.now() - 7200000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-105.122, 39.601],
          [-104.673, 39.601],
          [-104.673, 39.952],
          [-105.122, 39.952],
          [-105.122, 39.601],
        ],
      ],
    },
  },
  {
    id: 'mock-6',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-6',
      '@type': 'wx:Alert',
      id: 'mock-6',
      areaDesc: 'Boston, Essex, Middlesex, Norfolk, Plymouth, Suffolk, Worcester, MA',
      category: 'Met',
      response: 'Prepare',
      severity: 'Moderate',
      urgency: 'Expected',
      event: 'Winter Storm Warning',
      sender: 'W-NWS-NWSTG-1',
      senderName: 'NWS Boston MA',
      headline: 'Winter Storm Warning for Eastern Massachusetts',
      description: 'A winter storm warning is in effect from Saturday afternoon through Sunday morning. Heavy snowfall is expected with total accumulations of 6-10 inches. Coastal areas may experience mixed precipitation early, changing to all snow by evening.',
      instruction: 'Finish any necessary travel by Saturday afternoon. Stock up on essential supplies including food, water, and medications. Charge electronic devices in case of power outages.',
      messageType: 'Alert',
      certainty: 'Likely',
      url: 'https://weather.gov/box/winter',
      effective: new Date(Date.now() - 14400000).toISOString(),
      onset: new Date(Date.now() + 7200000).toISOString(),
      expires: new Date(Date.now() + 100800000).toISOString(),
      sent: new Date(Date.now() - 14400000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-71.380, 42.232],
          [-70.838, 42.232],
          [-70.838, 42.581],
          [-71.380, 42.581],
          [-71.380, 42.232],
        ],
      ],
    },
  },
  // Hurricane example
  {
    id: 'mock-hurricane-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-hurricane-1',
      '@type': 'wx:Alert',
      id: 'mock-hurricane-1',
      areaDesc: 'Miami-Dade, Broward, Palm Beach, Monroe, FL',
      category: 'Met',
      response: 'Evacuate',
      severity: 'Extreme',
      urgency: 'Immediate',
      event: 'Hurricane Warning',
      sender: 'W-NWS-NWSTG-6',
      senderName: 'NWS Miami FL',
      headline: 'Hurricane Warning for South Florida',
      description: 'A major hurricane is approaching South Florida. Sustained winds of 115 mph with gusts to 135 mph are expected. Storm surge of 6-8 feet above ground level is forecast for coastal areas.',
      instruction: 'Evacuate immediately if you are in a mandatory evacuation zone. Secure your home and move to higher ground. Follow local emergency management instructions.',
      messageType: 'Alert',
      certainty: 'Likely',
      url: 'https://weather.gov/mfl/hurricane',
      effective: new Date(Date.now()).toISOString(),
      onset: new Date(Date.now() + 10800000).toISOString(),
      expires: new Date(Date.now() + 172800000).toISOString(),
      sent: new Date(Date.now()).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-81.999, 25.383],
          [-80.823, 25.383],
          [-80.823, 26.253],
          [-81.999, 26.253],
          [-81.999, 25.383],
        ],
      ],
    },
  },
  // Flood example
  {
    id: 'mock-flood-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-flood-1',
      '@type': 'wx:Alert',
      id: 'mock-flood-1',
      areaDesc: 'St. Louis, St. Louis County, Jefferson, Franklin, MO',
      category: 'Met',
      response: 'Evacuate',
      severity: 'Severe',
      urgency: 'Immediate',
      event: 'Flash Flood Warning',
      sender: 'W-NWS-NWSTG-5',
      senderName: 'NWS St. Louis MO',
      headline: 'Flash Flood Warning for St. Louis Metro',
      description: 'Flash flooding is occurring in the St. Louis area due to heavy thunderstorms. Multiple roads are impassable due to high water. Several inches of rain have fallen in a short period of time.',
      instruction: 'Move to higher ground immediately if you are in a flood-prone area. Do not attempt to drive through flooded roads. Turn around, dont drown.',
      messageType: 'Alert',
      certainty: 'Observed',
      url: 'https://weather.gov/lsx/flood',
      effective: new Date(Date.now() - 3600000).toISOString(),
      onset: new Date(Date.now() - 1800000).toISOString(),
      expires: new Date(Date.now() + 7200000).toISOString(),
      sent: new Date(Date.now() - 3600000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-90.319, 38.414],
          [-90.107, 38.414],
          [-90.107, 38.676],
          [-90.319, 38.676],
          [-90.319, 38.414],
        ],
      ],
    },
  },
  // Wildfire example
  {
    id: 'mock-wildfire-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-wildfire-1',
      '@type': 'wx:Alert',
      id: 'mock-wildfire-1',
      areaDesc: 'Los Angeles, Ventura, San Bernardino, Riverside, CA',
      category: 'Fire',
      response: 'Evacuate',
      severity: 'Severe',
      urgency: 'Immediate',
      event: 'Wildfire Warning',
      sender: 'W-NWS-NWSTG-18',
      senderName: 'NWS Los Angeles CA',
      headline: 'Wildfire Warning for Southern California',
      description: 'A large wildfire is burning out of control in Southern California. Strong Santa Ana winds are contributing to rapid fire spread. Thousands of acres have already burned and multiple structures are threatened.',
      instruction: 'Evacuate immediately if ordered by authorities. Close all windows and doors, and turn off gas appliances if you have time. Check with local emergency management for evacuation routes.',
      messageType: 'Alert',
      certainty: 'Observed',
      url: 'https://weather.gov/lox/wildfire',
      effective: new Date(Date.now() - 7200000).toISOString(),
      onset: new Date(Date.now() - 5400000).toISOString(),
      expires: new Date(Date.now() + 86400000).toISOString(),
      sent: new Date(Date.now() - 7200000).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-118.945, 33.704],
          [-117.689, 33.704],
          [-117.689, 34.386],
          [-118.945, 34.386],
          [-118.945, 33.704],
        ],
      ],
    },
  },
  // Severe Thunderstorm example
  {
    id: 'mock-thunderstorm-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-thunderstorm-1',
      '@type': 'wx:Alert',
      id: 'mock-thunderstorm-1',
      areaDesc: 'Dallas, Tarrant, Collin, Denton, TX',
      category: 'Met',
      response: 'Prepare',
      severity: 'Severe',
      urgency: 'Immediate',
      event: 'Severe Thunderstorm Warning',
      sender: 'W-NWS-NWSTG-2',
      senderName: 'NWS Fort Worth TX',
      headline: 'Severe Thunderstorm Warning for North Texas',
      description: 'Severe thunderstorms are approaching North Texas with large hail up to golf ball size and damaging winds up to 70 mph. Heavy rain and frequent lightning are also expected.',
      instruction: 'Move indoors immediately. Stay away from windows. Secure outdoor objects that could be blown away. Avoid using landline phones during the storm.',
      messageType: 'Alert',
      certainty: 'Observed',
      url: 'https://weather.gov/fwd/thunderstorm',
      effective: new Date(Date.now()).toISOString(),
      onset: new Date(Date.now()).toISOString(),
      expires: new Date(Date.now() + 3600000).toISOString(),
      sent: new Date(Date.now()).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-97.449, 32.889],
          [-96.528, 32.889],
          [-96.528, 33.496],
          [-97.449, 33.496],
          [-97.449, 32.889],
        ],
      ],
    },
  },
  // Heat Advisory example
  {
    id: 'mock-heat-1',
    type: 'Feature',
    properties: {
      '@id': 'https://api.weather.gov/alerts/mock-heat-1',
      '@type': 'wx:Alert',
      id: 'mock-heat-1',
      areaDesc: 'Phoenix, Maricopa, Pinal, Yavapai, AZ',
      category: 'Met',
      response: 'Prepare',
      severity: 'Moderate',
      urgency: 'Expected',
      event: 'Excessive Heat Warning',
      sender: 'W-NWS-NWSTG-12',
      senderName: 'NWS Phoenix AZ',
      headline: 'Excessive Heat Warning for Arizona',
      description: 'Dangerous heat conditions are expected across Arizona with temperatures reaching 115-120 degrees. Heat index values could approach 125 degrees. This heat could be life-threatening, especially for vulnerable populations.',
      instruction: 'Stay indoors in air-conditioned spaces as much as possible. Drink plenty of water and avoid strenuous outdoor activities. Check on elderly family members and neighbors.',
      messageType: 'Alert',
      certainty: 'Likely',
      url: 'https://weather.gov/phx/heat',
      effective: new Date(Date.now()).toISOString(),
      onset: new Date(Date.now() + 7200000).toISOString(),
      expires: new Date(Date.now() + 259200000).toISOString(),
      sent: new Date(Date.now()).toISOString(),
      status: 'Actual',
      notification: 'NWS',
      references: [],
    },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-112.338, 32.846],
          [-111.084, 32.846],
          [-111.084, 34.386],
          [-112.338, 34.386],
          [-112.338, 32.846],
        ],
      ],
    },
  },
];

// Function to get mock alerts by state
export function getMockAlertsByState(state: string): WeatherAlert[] {
  return mockAllAlerts.filter(alert => 
    alert.properties.areaDesc.includes(state)
  );
}

// Function to get all mock alerts
export function getAllMockAlerts(): WeatherAlert[] {
  return mockAllAlerts;
}

// Function to simulate random alert updates
export function getRandomMockAlerts(count: number = 3): WeatherAlert[] {
  const shuffled = [...mockAllAlerts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
